### ISSUE TITLE
Scroll behaves differently in Firefox and Chrome (desktop)

### ISSUE THREAD

**Issue by bitinn** [forcedotcom/scrollerjs#1]
Firefox scrolls much more slowly than Chrome (when using mouse wheel).

**Comment by diervo** [comment]
Scroll wheel is quite diffferent depending on the platform and also on the peripheral (mouse, trackpad) that you use. I will take a look and try to make some improvements soon. Will try to make it for next release at the end of the month.

**Comment by bitinn** [comment]
Thx for the reply, I was curious if this was a known limit (given the focus is on mobile).

FYI:
- Firefox issue confirmed on Win8 and OSX
- Browser smooth scroll setting does not affect outcome.
- IE11 and Chrome doesn’t suffer from the same problem
- Also trackpad scroll is not affected (at least on Macbook Air).

so likely has something to do with how firefox fire mouse wheel event.

**Comment by webdesignberlin** [comment]
As bitinn said:

> Firefox scrolls much more slowly than Chrome (when using mouse wheel).

On Firefox 38.0.5 & Firefox Developer Edition 40.0a2 (2015-05-26) it scrolls very slow (it doesnt work). I got an Error: TypeError: STYLES.matrix is not a constructor

**Comment by diervo** [comment]
Closing this this browser versions are very old already.
