### ISSUE TITLE
Playground examples don't scroll on Android Galaxy SIII default browser

### ISSUE THREAD

**Issue by b4codify** [forcedotcom/scrollerjs#10]
Device: Samsung Galaxy SIII (4.3)
Browser: Default Android browser (Internet)

None of the samples provided in playground scrolls over default "Internet" browser.

Note: All of these samples work perfectly fine over downloaded "Chrome" browser on same Android device.

**Comment by karneaud** [comment]
I concur also on Asus TF101 running 4.01. However I have an AOC Breeze running Android 2.3 and runs fairly well on stock browser.

**Comment by diervo** [comment]
I don't have time neither the resources to investigate those issues. If you guys can found the root cause fine, otherwise this is a no fix.
