### ISSUE TITLE
Surface pool wrong management

### ISSUE THREAD

**Issue by sucotronic** [forcedotcom/scrollerjs#14]
With the example-carousel-indicator.html if you execute the following javascript:

```
for (var i=0; i<10000;i++)
    scroller.appendItems("<div>item"+i+"</div>")
```

and the user uses the scroll indicator multiple times to navigate, the pool is increased instead of being re-used (see video: http://tinypic.com/r/2utrrcn/8)

**Comment by diervo** [comment]
The problem is that the size of the items you are inserting is really small and therefore you need a lot of surface to fullfill the space till is time for shift or pop again. The pool management is correct.
If you do this: 

``` javascript
for (var i=0; i<10000;i++) {
    scroller.appendItems("<div style="width:320px">item"+i+"</div>");
}
```

You will see that the management is correct as well.
