### ISSUE TITLE
Surfaces dom entries are created for every row!

### ISSUE THREAD

**Issue by JeremyColton** [forcedotcom/scrollerjs#35]
1. Is there a way to set the max number of 'surface' divs in the viewport? Eg +1 top/bottom just outside the viewport.  Currently, I see 6 additional non-viewable 'surface' divs created which are not needed.

2. In your youtube video, how are you adding rows to the Scroller object - via window.scroller.prependItems() ?

Many thanks

**Comment by JeremyColton** [comment]
1. I thought that this scroller only creates enough surfaces to fill the viewport.  As the user scrolls up/down, surfaces are recycled with new row's contents and moved via CSS3 translation.  This keeps the DOM entries to a minimum while enjoying GPU accelerated painting. Correct?

Currently, I see a 'surface' div per row which kills the performance when there are 100s of rows and defeats the point of an infinite scroll.

2. Is there a way to set the max number of 'surface' divs in the viewport?

3. In your youtube video, how are you adding rows to the Scroller object - via window.scroller.prependItems() ?

Many thanks

**Comment by diervo** [comment]
Sorry for the loong delay in the response, this project its been in stand by mode for a while.
1. The surfaces are calculated based on the available viewport area.
2. Yes in the examples you can find the exact code.
