### ISSUE TITLE
Scrolling always starts with a small jump

### ISSUE THREAD

**Issue by skyostil** [forcedotcom/scrollerjs#8]
Tested with Chrome M37 on a Nexus 5.
1. Open any of the examples on scrollerjs.com (e.g., Default).
2. Put a finger down on the display and start moving it slowly.

This causes the page to abruptly jump to the direction you are moving and then start scrolling smoothly. I think this is a problem of not accounting correctly for the "touch slop" [1] area in the first scroll delta.

[1] http://developer.android.com/reference/android/view/ViewConfiguration.html#getScaledTouchSlop()

**Comment by diervo** [comment]
You can define the thresholds you want for that:
https://github.com/forcedotcom/scrollerjs/blob/development/src/scroller.js#L123-L125

**Comment by skyostil** [comment]
Thanks for the pointer. To be clear, the bug is that even with a non-zero threshold, scrolling should always start smoothly without a jump. In other words, the threshold needs to be subtracted from the first scroll delta to avoid a discontinuity. This is how native scrolling works on both Android and iOS.
