### ISSUE TITLE
Infinite Loading Plugin

### ISSUE THREAD

**Issue by duncanreid** [forcedotcom/scrollerjs#9]
I think scrollWidth & scrollHeight are in the wrong spot in the infinite loading plugin, no?
Line 115:

``` javascript
if (this.scrollVertical) {
    pos  = y;
    size = this.scrollerWidth;
} else {
    pos  = x;
    size = this.scrollerHeight;
}
```

**Comment by diervo** [comment]
Thanks! 
FIxed here:
https://github.com/forcedotcom/scrollerjs/commit/30c0291d1571d81e20720623105dc9f0745ac396
